### ISSUE TITLE
Definitions, Legal & Regulatory Considerations

### ISSUE THREAD

**Issue by NRSchaaf** [NRSchaaf/FreshRoutes#2]
As a Business Owner, I need to understand the key terminology for the business plan and if there are any legal or regulatory requirements that we need to adhere to so that we can be in compliance with the law, include such considerations in our financial plan, and have a reference list of key terms for presentations and marketing.

- What is a food desert?
- What does "low income" mean?
- What does "underserved populations" mean in regard to groceries?
- What applicable law, regulations and health codes do we need to consider?

**Comment by amartian1** [comment]
1. A food desert is an area, often urban or rural, where residents have limited access to affordable and nutritious food, especially fresh fruits and vegetables. These areas typically lack supermarkets, grocery stores, or farmers’ markets that offer healthy food options, forcing residents to rely on convenience stores and fast food outlets that often sell mostly processed, unhealthy foods.

Key characteristics of food deserts include:

	•	Distance from Healthy Food Sources: Residents must travel significant distances (often more than a mile in urban areas or 10 miles in rural areas) to reach a supermarket or grocery store.
	•	Low-Income Communities: Food deserts are often found in low-income neighborhoods where many residents may not have access to a car, making it even harder to travel to stores with healthier food options.
	•	Health Impacts: The lack of access to nutritious food can lead to higher rates of diet-related health issues, such as obesity, diabetes, and heart disease.

Addressing food deserts involves improving access to healthy foods through initiatives like mobile markets, community gardens, better public transportation to grocery stores, and encouraging the establishment of supermarkets in underserved areas.

2. In the context of food deserts, low income refers to households or communities where residents earn less than the median income level and often struggle to afford basic needs, including nutritious food. Specifically, the term is often defined by criteria set by governmental or research organizations, such as:

- Federal Poverty Level (FPL): Households that earn below a certain percentage of the FPL (often set at 200% or lower) are considered low-income. This threshold can vary by household size and location.
- Area Median Income (AMI): Households earning less than a specific percentage of the AMI, such as 80% or lower, are considered low-income. This metric takes into account the average income within a specific area, such as a city or county.
- Eligibility for Assistance Programs: Households that qualify for government assistance programs like SNAP (Supplemental Nutrition Assistance Program), WIC (Women, Infants, and Children), or free/reduced school lunch programs often fall under the low-income category.
- High Unemployment or Underemployment Rates: Areas with high levels of unemployment, part-time, or low-wage work often have a higher concentration of low-income residents.

In food deserts, low income often intersects with a lack of accessible, affordable, healthy food options, creating a barrier for residents who may want to eat healthily but cannot afford or easily obtain fresh, nutritious food.

3. In the context of groceries, underserved populations refer to groups of people who lack adequate access to grocery stores, supermarkets, or other sources of fresh, nutritious food. These populations face barriers that limit their ability to purchase healthy food, often due to economic, geographic, social, or transportation challenges. Key characteristics of underserved populations in regard to groceries include:

- Geographic Barriers: These populations live in areas with few or no grocery stores, often referred to as food deserts. This is common in both urban neighborhoods without nearby supermarkets and rural areas where stores are spread far apart.
- Economic Barriers: Many underserved populations are low-income and may struggle to afford groceries, particularly fresh produce, whole grains, and lean proteins, which are often more expensive than processed foods.
- Transportation Challenges: Without reliable access to transportation, such as cars or public transit, residents may find it difficult to travel to grocery stores that offer a variety of healthy food options.
- Cultural or Language Barriers: Populations such as immigrants or ethnic minorities may find that nearby stores do not carry culturally appropriate foods or that they lack staff who speak their language, further complicating access.
- Health and Mobility Issues: Elderly or disabled individuals may have difficulty traveling to or navigating grocery stores, making it harder for them to obtain healthy foods.

Addressing the needs of underserved populations involves increasing access to grocery stores, offering affordable and culturally appropriate food options, enhancing public transportation, and implementing programs like mobile markets or delivery services that bring healthy foods directly to these communities.

4. In North Carolina, operating a grocery store or any food retail business involves complying with various laws, regulations, and health codes to ensure food safety, legal operation, and consumer protection. Here’s an overview of the key legal and regulatory considerations specific to North Carolina:

Food Safety Regulations

- North Carolina Food, Drug, and Cosmetic Act: This state law regulates the safety of food products, aligning with federal standards to prevent adulteration and ensure proper labeling.
- North Carolina Food Code: Based on the FDA Food Code, it provides guidelines for food handling, preparation, storage, and sanitation in retail food establishments, including grocery stores.
- North Carolina Department of Health and Human Services (NCDHHS): Oversees inspections of food establishments to ensure compliance with health and safety standards. Regular inspections are conducted to ensure safe food handling practices.

Licensing and Permitting

- Business Licenses: All grocery stores must obtain a general business license from the city or county where they operate.
- Food Establishment Permits: Issued by local health departments, these permits are required to operate any facility that handles, prepares, or serves food. Permits are subject to regular inspections to maintain compliance with health codes.
- Alcohol Sales Permit: If the store plans to sell alcoholic beverages, it must obtain a permit from the North Carolina Alcoholic Beverage Control (ABC) Commission.

Zoning and Land Use

- Local Zoning Ordinances: Governing where grocery stores can be located within a city or county. Zoning laws dictate acceptable locations, building codes, and requirements specific to the type of business.
- Special Use Permits: May be required if the grocery store location is in a zone that requires additional approval for food retail operations.

Health and Sanitation Codes

- Sanitation Standards: Enforced by local health departments, these standards cover requirements for cleanliness, pest control, waste disposal, and employee hygiene.
- Food Handling Certification: Grocery stores must ensure that employees involved in food preparation and handling are trained and certified in food safety, often through programs like ServSafe.

Nutrition Assistance Programs

- SNAP and WIC Authorization: Stores that wish to accept Supplemental Nutrition Assistance Program (SNAP) or Women, Infants, and Children (WIC) benefits must be authorized by the USDA and comply with federal and state regulations governing these programs.
- Compliance with North Carolina EBT (Electronic Benefits Transfer): Stores must have the proper equipment and authorization to process EBT transactions for SNAP recipients.

Environmental and Waste Management Regulations

- North Carolina Solid Waste Management Rules: Regulates the disposal of food waste, packaging, and other materials. Grocery stores must comply with these rules, including recycling requirements and disposal of hazardous materials.
- Grease Trap Regulations: Stores with deli or prepared food sections may need to comply with local wastewater regulations, including the installation and maintenance of grease traps.

Consumer Protection and Labelling

- Weights and Measures Regulations: Enforced by the North Carolina Department of Agriculture and Consumer Services (NCDA&CS), these regulations ensure the accuracy of scales, price scanners, and other measuring devices in stores.
- Labelling Requirements: Ensures that food products are properly labeled with ingredients, allergens, nutritional information, and expiration dates according to both state and federal standards.

Employment and Labor Laws

- North Carolina Wage and Hour Act: Governs minimum wage, overtime, and working conditions for employees.
- Workplace Safety Regulations: Compliance with Occupational Safety and Health Administration (OSHA) standards and state-specific workplace safety requirements.

These laws and regulations are essential for legally operating a grocery store in North Carolina, ensuring the health and safety of customers, and maintaining compliance with local and state guidelines.
